name: Unstable Commit Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build dev-latest

      - name: Upload unstable build
        uses: ncipollo/release-action@v1
        with:
          tag: unstable
          name: Unstable Commit Build
          body: |
            **Latest Unstable build**  
            Built from commit: ${{ github.sha }}
            
            Contains the latest features that are not yet ready for production.
            May contain bugs or issues. Not stable for production use.


            - Branch: ${{ github.ref_name }}
            - Triggered by: ${{ github.actor }}
          artifacts: teamsPlus versions/teams_plus@dev-latest.zip
          draft: false
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true